contentDir="topics"
baseURL = "/"
title = "Maistra.io"
theme = "hugo-theme-learn-master"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = false
ignorefiles=["DRAFTS/.*"]
languageCode = "en-US"
alwaysopen=true

# make URLs ending in .html
uglyurls = true

# Disqus Username
disqusShortname = "disqus_shortname"
# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Docs"
  weight = 1
  identifier = "docs"
  url = "/docs/"

[[menu.main]]
  name = "Contribute"
  weight = 3
  identifier = "contribute"
  url = "/contribute/"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/maistra"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/maistraio"
    name = "twitter"
    weight = 2

[params]
  themeVariant="blue"
  ordersectionsby="weight"
  disableBreadcrumb = true
  disableNextPrev = true
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true


  accent = "#006264"
  backgroundColor = "#f5f5f5"
  highlightLanguages = ["r", "bash", "go", "yaml"]

  # Sets the meta tag description
  description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Maistra"

[Languages]
[Languages.en]
title = "Maistra.io -- Istio for OpenShift"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/maistra/istio"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Contribute"
url = "/contribute"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON"]
